### ISSUE TITLE
direct link to ticket for agents using auth cas

### ISSUE THREAD

**Issue by bpalme** [kevinoconnor7/osTicket-auth-cas#11]
Hi Kevin,
Direct links to a certain ticket (like clicking on a link from an email notification) doesn't seem to be working on the agent side with CAS.  I'm using  1.10-rc.2 and I'm pretty sure I'm using 1.1.2 for the plugin.  How hard would that be to get working?  Or should it be working already...

Thanks!
Brent

**Comment by kevinoconnor7** [comment]
Can you expand on what the exact issue is? I just tried it in my test environment and clicking a link in an e-mail brought me directly to the ticket screen if I was already logged in. If I'm not logged in the it brings me to the login screen where there is a Login with CAS button.

I did notice that after logging in it doesn't then bring me to the ticket. I believe that's a bug with osTicket though.

**Comment by bpalme** [comment]
Right, after logging in with CAS I can't get to the ticket.  If I log in without using CAS (local account) then I am taken to the ticket afterwards.  That's why I thought maybe you might have some control over that.  Could be in OS Ticket though.  If you have any info on that, I'd appreciate it.

**Comment by bpalme** [comment]
maybe something like this?:
when the link to CAS is generated, it adds the ticket ID to the parameters do and bak.
In scp/login.php the call to triggerAuth passes that ticket ID in
then in triggerAuth(), if you've gotten the ID passed back in, you redirect to ticket.php with the parameter instead of /scp

You can override renderExternalLink() right?  So the hard part is getting them to change the interface for the function triggerAuth() to allow for the parameter to be passed in.

any good?

**Comment by kevinoconnor7** [comment]
Turns out it was a bug in that I was redirecting back to `scp/` rather than `scp/login.php` that latter of which didn't handle the destination redirect. d0cb92657ff4c65ea424622399cc417a553b21ef should handle this correctly, and I pushed v1.1.4 that has the fix rolled in.
