### ISSUE TITLE
CAS Authentication for agents

### ISSUE THREAD

**Issue by bastienho** [kevinoconnor7/osTicket-auth-cas#13]
Hi

it seems that the bug solved in #5 and mentioned in #8 still occurs, even on develop-next
- Client can login against CAS
- Agents are always redirected to the login page with notice: 

> Authentication required

The first time

> Have your administrator create a local account

other times

**Comment by kevinoconnor7** [comment]
The second error implies that the matching agent account cannot be found. This usually means that the CAS username and the osTicket username don't match up perfectly. You have two options:
1. If you provide the e-mail address via CAS extended attributes you can configure the plugin with the attribute key to use.
2. If you don't provide it via extended attributes, you can hard code the e-mail suffix you want appended to usernames.

**Comment by bastienho** [comment]
Thank you

But it worked until OsTicket 1.8, and it still work for end users

**Comment by kevinoconnor7** [comment]
Hmm, something else is going on. I'll try to reproduce this later tonight.

However, this is a different issue than those two linked bugs. In this case your agents are fail authentication.

**Comment by kevinoconnor7** [comment]
I wasn't able to reproduce this locally on latest commit in develop-next. Have any other settings changed in your environment? Are you using the latest version of the plugin?

**Comment by bastienho** [comment]
Hi,
Sorry, after almost an entire day trying to make it work, I finally have a good result on the evening.

And I don't know exactly what happened. 

First, I had both front and back broken with CAS, just getting a 404 when calling the api 

And after a server (Nginx) reconfiguration, it fell in work.

Thank you for your work.
