### ISSUE TITLE
Incompatible with osT v 1.10 

### ISSUE THREAD

**Issue by cfarnham1** [kevinoconnor7/osTicket-auth-cas#14]
Installed plugin via phar while testing the latest stable release of osTicket v1.10. I no longer get the button to "Login with CAS." 

Looks like this has been out of development for a little while but I figured I would post this anyway because I love this plugin for osTicket 1.9.

In any case, great plugin and thanks kevin!

**Comment by kevinoconnor7** [comment]
I'll take a look this weekend.

In general this plugin is feature complete so very few updates are pushed these days. I also no longer work where I originally developed and deployed this plugin so I haven't kept up on osTicket releases.

Thanks for letting me know :)

**Comment by cfarnham1** [comment]
I'm gonna mess around with it too to see what might be missing. Also I'm sorry, I should have included this in the first post, the working version I am upgrading from is v1.9.9

**Comment by kevinoconnor7** [comment]
So I bumped my dev environment up the the stable 1.10 release and I don't see any issues. I had last tested it on one of the 1.10 RC releases.

Perhaps try reinstalling the plugin? Double check the plugin settings?

If you're still having issues, check to see if your server logs contain any clues.

**Comment by cfarnham1** [comment]
Just an update on this. I was finally able to do a fresh installation from 1.9 to 1.10 rather than an upgrade and it's working again! Thanks Kevin!

**Comment by kevinoconnor7** [comment]
Glad to hear things worked out :)
