### ISSUE TITLE
single sign out not working

### ISSUE THREAD

**Issue by informatico-madrid** [kevinoconnor7/osTicket-auth-cas#27]
Hi

When i have a logout petitión from CAS to close sessión. sessión its still open.

Do you can tell me, where we have relation user sessión id stored  with ticket in samlp:SessionIndex key of XML in POST parameter of SIngle sing out petitión From CAS

**Comment by kevinoconnor7** [comment]
Are you referring to single sign out or server logout? The latter is not supported, see #24.

**Comment by informatico-madrid** [comment]
thankx
