### ISSUE TITLE
OSTicket 1.10 RC2 / osTicket-auth-cas -> Error

### ISSUE THREAD

**Issue by PPCM** [kevinoconnor7/osTicket-auth-cas#4]
Hello,

This plugin is a great idea, but when I install it with OSTicket v1.10-rc.2, after the installation and activation, OSTicket crash and I have the following error:
PHP Fatal error:  Can't use method return value in write context in phar:///home/ticket_sictiam/www/upload/include/plugins/auth-cas.phar/cas.php on line 153

Versions:
PHP 5.4.45
Apache 2.2.22

Any idea?

Thanks a lot

**Comment by kevinoconnor7** [comment]
Thanks for letting me know! Should be solved in 6204a546c7f4df082872f978ce9bad99415ae1d4 and the latest release (v1.1.1) should have the fix ready to go for you!
