### ISSUE TITLE
After CAS Authentificate, return to OSTicket login page

### ISSUE THREAD

**Issue by PPCM** [kevinoconnor7/osTicket-auth-cas#5]
Hi,

After installation of osTicket-auth-cas 1.1.1, configuration was made and a user with SSO CAS auth was created
On OSTicket login page the button "Sign with CAS" is present, after a click on that button, the authentification can be made on SSO CAS Server.
The return page is once again the login page of OSTicket, and the CAS user must click on "Sign with CAS" button to finaly access to tickets page.

It will be great if the return page can be the tickets page of OSTicket and not the login page.

**Comment by kevinoconnor7** [comment]
To confirm, are you using the osticket 1.10 RC? Also, is the issue when a user is logging into the stafff control panel?

If so this is a bug with osticket. I filed a [PR](https://github.com/osTicket/osTicket-1.8/pull/2641) with them yesterday. Feel free to manually apply that PR to fix it.

**Comment by PPCM** [comment]
Thanks, I confirm, I am using OSTicket 1.10 RC2

Now it is perfect for Agents...
(I will post an issue for clients ;-) )

**Comment by bastienho** [comment]
Hi

it seems that the bug still occurs, even on *develop-next*

- Client can login against CAS
- Agents are always redirected to the login page with notice:
>  Authentication required

The first time

> Have your administrator create a local account

other times
