### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by PPCM** [kevinoconnor7/osTicket-auth-cas#6]
If it can help, here are translation of all labels used by the plugin in French:
- Server Hostname -> Nom du serveur
- Server Port: -> Port du serveur
- Server Context -> Chemin du service SSO CAS
- This value is "/cas" for most installs. -> Cette valeur est "/cas" pour la plupart des installations.
- CA Cert Path -> Chemin Certificat AC
- E-mail suffix -> Suffixe de l'email
- Use this field if your CAS server does not report an e-mail attribute. ex: "@domain.tld" -> Utiliser ce champ if le serveur CAS ne transmet pas l'attribut email. ex: "@domain.tld"
- Name attribute key -> Valeur de l'attribut Nom
- E-mail attribute key -> Valeur de l'attribut email
- Use single sign off -> Utiliser la déconnexion du SSO
- Authentication -> authentification
- Disabled -> Désactivé
- Agents Only -> Agents uniquement
- Clients Only -> Utilisateurs uniquement
- Agents and Clients -> Agents et Utilisateurs
- Sign in with CAS -> Connexion avec SSO CAS

Hope it can help

**Comment by kevinoconnor7** [comment]
Sorry for the delay, your contribution is very much appreciated!

I've setup [Crowdin](https://crowdin.com/project/osTicket-auth-cas) for this project and have loaded your translated strings. Starting with the next release of the plugin the messages should be included.
