### ISSUE TITLE
Not  available

### ISSUE THREAD

**Issue by dsapikas** [kevinoconnor7/osTicket-auth-cas#9]
I Installed the latest version of osTicket on a simple stack (ubuntu 14.04 LTS) with the latest Sentora, osTicket works fine, i uploaded the auth-cas.phar on include/plugins/auth-cas.phar, when i go to the Admin Panel -> Manage Plugins -> Add new Plugin, there is an empty list.

**Comment by kevinoconnor7** [comment]
Things to check:
1. What version of osTicket are you running?
2. What PHP version?
3. Can you confirm that the phar is readable by the user running apache or PHP-FPM (whichever is applicable)?
4. Can you tell me what your `phar.*` runtimes settings are? You can either get them from your php.ini or use `<?php phpinfo(); ?>` to get that.

**Comment by dsapikas** [comment]
Hello @kevinoconnor7 , here are the specs : 
1. osTicket (v1.9.12)
2. PHP 5.5.9-1ubuntu4.14
3. I made it 777 just in case.
4. [phpinfo.pdf](https://github.com/kevinoconnor7/osTicket-auth-cas/files/36498/phpinfo.pdf)

**Comment by kevinoconnor7** [comment]
Sorry, I've been busy these last few weeks and didn't get a chance to review this. I don't see anything wrong from your config. Can you maybe bump up the php_error level and see if any errors/warnings are being generated?
